import scrapy
import urllib.parse
import os


class CnnSpider(scrapy.Spider):
    name = "cnn"
    start_urls = [
        'https://edition.cnn.com/2021/02/12/health/cdc-covid-19-reopening-schools-recommendations-bn/index.html',
        'https://edition.cnn.com/2021/02/12/health/us-kids-red-zones-cdc-school-guidelines/index.html',
        'https://edition.cnn.com/2021/02/12/health/vaccines-good-news-severe-disease-variants-gupta/index.html',
        'https://edition.cnn.com/2021/02/12/health/covid-19-vaccine-comorbidities-states-cnn-analysis-wellness/index.html',
        'https://edition.cnn.com/2021/02/12/health/vitamin-c-zinc-covid-19-wellness/index.html',
        'https://edition.cnn.com/2021/02/09/health/pandemic-peak-whats-next/index.html',
        'https://edition.cnn.com/2021/02/12/health/climate-change-allergies-wellness/index.html',
        'https://edition.cnn.com/2021/02/11/health/us-coronavirus-thursday/index.html',
        'https://edition.cnn.com/2021/02/12/health/caregivers-covid-vaccine-khn-partner-wellness/index.html',
        'https://edition.cnn.com/2021/02/11/health/tocilizumab-rheumatoid-arthritis-covid-19-treatment/index.html',
        'https://edition.cnn.com/2021/02/10/health/double-masking-cdc-study-escape-wellness/index.html',
        'https://edition.cnn.com/2021/02/11/health/new-cdc-guidance-schools-anticipated/index.html',
        'https://edition.cnn.com/2021/01/28/health/variants-coronavirus-new-popping/index.html',
        'https://edition.cnn.com/2021/02/13/health/galentines-day-self-love-wellness/index.html',
        'https://edition.cnn.com/2021/02/13/health/us-coronavirus-saturday/index.html'
        'https://edition.cnn.com/2021/02/12/health/us-coronavirus-friday/index.html',
        'https://edition.cnn.com/2021/02/12/health/federal-retail-pharmacy-chain-vaccine-rollout/index.html',
        'https://edition.cnn.com/2021/02/12/health/cdc-listeria-warning-hispanic-style-cheeses/index.html',
        'https://edition.cnn.com/2021/02/10/health/us-coronavirus-wednesday/index.html',
        'https://edition.cnn.com/2021/02/10/health/alabamas-black-population-vaccine-eligibility/index.html',
        'https://edition.cnn.com/2021/02/10/health/covid-vaccinated-quarantine-cdc-guidance/index.html',
        'https://edition.cnn.com/2021/02/10/health/weight-loss-diabetes-drug-injected-wellness/index.html',
        'https://edition.cnn.com/2021/02/09/health/face-mask-guidance-coronavirus-wellness/index.html',
        'https://edition.cnn.com/2021/02/10/health/how-to-celebrate-valentines-day-pandemic-wellness/index.html',
        'https://edition.cnn.com/2021/02/10/health/covid-vaccine-seniors-coronavirus/index.html',
        'https://edition.cnn.com/2021/02/10/health/who-covid-global-cases-decline-intl/index.html',
        'https://edition.cnn.com/2021/02/10/health/risk-of-covid-19-public-perception-poll-wellness/index.html',
        'https://edition.cnn.com/2021/02/10/health/kids-mental-health-suicide-pandemic-wellness/index.html',
        'https://edition.cnn.com/2021/02/09/health/us-coronavirus-tuesday/index.html',
        'https://edition.cnn.com/2021/02/09/health/second-dose-covid-19-vaccine-hurdles-us-wellness/index.html',
        'https://edition.cnn.com/2021/02/08/health/us-coronavirus-monday/index.html',
        'https://edition.cnn.com/2021/02/08/health/covid-19-antigen-tests-states-cnn-analysis/index.html',
        'https://edition.cnn.com/2021/02/01/health/us-coronavirus-monday/index.html',
        'https://edition.cnn.com/2021/02/08/health/habits-to-reduce-stress-pandemic-wellness/index.html',
        'https://edition.cnn.com/2021/02/07/health/south-africa-astrazeneca-vaccine-study/index.html',
        'https://edition.cnn.com/2021/02/09/health/coronavirus-flu-spread-cdc-wellness/index.html',
        'https://edition.cnn.com/2021/02/08/health/coronavirus-native-americans-internet-khn-wellness-partner/index.html',
        'https://edition.cnn.com/2021/02/09/health/eggs-good-or-bad-wellness/index.html',
        'https://edition.cnn.com/2021/02/09/health/peanut-allergy-study-scn/index.html',
        'https://edition.cnn.com/2021/02/05/health/cancer-patients-covid-vaccine-wellness/index.html',
        'https://edition.cnn.com/2021/02/09/health/south-africa-variant-vaccine-research/index.html',
        'https://edition.cnn.com/2021/02/09/health/dating-covid-vaccine-wellness/index.html',
        'https://edition.cnn.com/2021/02/09/health/black-coffee-benefits-wellness/index.html',
        'https://edition.cnn.com/2021/02/13/us/third-grader-legislation-hearing-loss-trnd/index.html',
        'https://edition.cnn.com/2021/02/04/us/covid-19-vaccine-drug-stores/index.html',
        'https://edition.cnn.com/2020/12/25/health/covid-19-negative-test-travel-restrictions-uk-us/index.html',
        'https://edition.cnn.com/2020/12/25/health/boston-health-care-worker-allergic-reaction-moderna-coronavirus-vaccine/index.html',
        'https://edition.cnn.com/2020/12/23/health/vaccine-rollout-slow-data-lags/index.html',
        'https://edition.cnn.com/2020/12/22/health/uk-coronavirus-variant-surveillance/index.html',
        'https://edition.cnn.com/2020/12/24/health/fauci-80th-birthday-christmas/index.html',
        'https://edition.cnn.com/2021/01/01/health/us-coronavirus-friday/index.html',
        'https://edition.cnn.com/2021/01/01/health/new-years-resolutions-wellness/index.html',
        'https://edition.cnn.com/2020/12/31/health/us-coronavirus-thursday/index.html',
        'https://edition.cnn.com/2020/12/31/health/california-covid-hospitals-catastrophe/index.html',
        'https://edition.cnn.com/2020/12/31/health/how-states-are-getting-vaccine-to-elderly-trnd/index.html',
        'https://edition.cnn.com/2020/12/31/health/clinking-glasses-toast-meaning-wellness-partner/index.html',
        'https://edition.cnn.com/2020/12/31/health/new-years-day-ideas-home-wellness/index.html',
        'https://edition.cnn.com/2020/12/30/health/colorado-uk-coronavirus-variant/index.html',
        'https://edition.cnn.com/2020/12/30/health/moderna-workforce-vaccine-questions/index.html',
        'https://edition.cnn.com/2020/12/30/health/us-uk-israel-covid-vaccinations/index.html',
        'https://edition.cnn.com/2020/12/30/health/uk-us-israel-vaccinations-explainer/index.html',
        'https://edition.cnn.com/2020/12/29/health/new-dietary-guidelines-us-wellness/index.html',
        'https://edition.cnn.com/2020/12/30/health/new-years-eve-ideas-home-wellness/index.html',
        'https://edition.cnn.com/2020/12/30/health/lisa-feldman-barrett-brain-science-wellness-scn/index.html',
        'https://edition.cnn.com/2020/12/30/health/new-years-eve-parties-covid-safety/index.html',
        'https://edition.cnn.com/2020/12/29/health/us-coronavirus-tuesday/index.html',
        'https://edition.cnn.com/2020/12/29/health/yoga-for-energy-wellness/index.html',
        'https://edition.cnn.com/2020/11/13/health/weather-warm-winter-clothes-wellness/index.html',
        'https://edition.cnn.com/2020/12/30/health/us-coronavirus-wednesday/index.html',
        'https://edition.cnn.com/2020/12/30/health/gallery/new-years-eve-movie-scene-wellness/index.html',
        'https://edition.cnn.com/2020/12/29/health/quarantine-after-holiday-travel-covid-wellness/index.html',
        'https://edition.cnn.com/2020/12/28/health/us-coronavirus-monday/index.html',
        'https://edition.cnn.com/2020/12/28/health/novavax-covid-vaccine-trial-phase-3/index.html',
        'https://edition.cnn.com/2020/12/28/health/nose-picking-coronavirus-transmission-wellness/index.html',
        'https://edition.cnn.com/2020/12/28/health/coronavirus-unknown-facts-intl-hnk-dst/index.html',
        'https://edition.cnn.com/2020/12/28/health/top-2020-health-stories-missed-wellness/index.html',
        'https://edition.cnn.com/2020/12/27/health/us-coronavirus-sunday/index.html',
        'https://edition.cnn.com/2020/12/27/health/rosary-religious-prayer-beads-wellness/index.html',
        'https://edition.cnn.com/2020/12/26/health/us-coronavirus-saturday/index.html',
        'https://edition.cnn.com/2020/12/26/health/mosquito-bites-human-disease-wellness-scn/index.html',
        'https://edition.cnn.com/2020/12/25/health/workout-when-sick-yoga-wellness/index.html',
        'https://edition.cnn.com/2020/12/24/health/cannabis-vaping-cough-bronchitis-vaping-wellness/index.html',
        'https://edition.cnn.com/2020/12/24/health/loss-of-smell-covid-test-wellness-partner/index.html',
        'https://edition.cnn.com/2020/12/23/health/us-coronavirus-wednesday/index.html',
        'https://edition.cnn.com/2020/12/23/health/coronavirus-uk-variant-vaccines-less-effective-prevent-covid-19/index.html',

        'https://edition.cnn.com/2020/12/13/health/covid-19-vaccines-can-begin-cdc-recommendation/index.html',
        'https://edition.cnn.com/2020/12/12/health/cdc-vaccine-committee-pfizer-vaccine-vote/index.html',
        'https://edition.cnn.com/2020/12/12/health/covid-vaccine-fda-cut-corners/index.html',
        'https://edition.cnn.com/2020/12/11/health/covid-vaccine-fda-eua/index.html',
        'https://edition.cnn.com/2020/12/11/health/pfizer-vaccine-what-we-know/index.html',
        'https://edition.cnn.com/2020/12/09/health/covid-vaccine-allergies-health-workers-uk-intl-gbr/index.html',
        'https://edition.cnn.com/2020/12/14/health/us-coronavirus-monday/index.html',
        'https://edition.cnn.com/2020/12/14/health/gm-pig-fda-approved/index.html',
        'https://edition.cnn.com/2020/12/14/health/us-covid-deaths-300k/index.html',
        'https://edition.cnn.com/2020/12/14/health/mask-covid-19-safety-vaccine-wellness/index.html',
        'https://edition.cnn.com/2020/12/14/health/home-covid-hotspot-study-wellness/index.html',
        'https://edition.cnn.com/2020/12/13/health/covid-vaccine-rollout-messy/index.html',
        'https://edition.cnn.com/2020/11/30/health/covid-vaccine-questions-when/index.html',
        'https://edition.cnn.com/2020/12/14/health/uk-blood-donation-gay-bisexual-men-scli-gbr-intl/index.html',
        'https://edition.cnn.com/2020/12/14/health/vaccine-what-not-to-do-covid-19/index.html',
        'https://edition.cnn.com/2020/12/14/health/start-a-journal-diary-wellness-wisdom-project/index.html',
        'https://edition.cnn.com/2020/12/14/health/how-to-celebrate-christmas-on-a-budget-wellness/index.html',
        'https://edition.cnn.com/2020/12/13/health/us-coronavirus-sunday/index.html',
        'https://edition.cnn.com/2020/12/11/health/pfizer-vaccine-what-we-know/index.html',
        'https://edition.cnn.com/2020/12/12/health/us-coronavirus-saturday/index.html',
    ]

    def parse(self, response):
        paragraphs = response.css('.zn-body__paragraph::text').getall()
        summary = response.xpath('//meta[contains(@name, "description")]').attrib['content']
        yield {
            'text': "".join(paragraphs),
            'summary': summary,
        }